name: Build and Push to Docker for Arm64 and AMD64

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]


jobs:
    build-and-push:
      name: Build and Push Docker Images
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/custom_web_vscode:latest
              ${{ secrets.DOCKER_USERNAME }}/custom_web_vscode:${{ github.sha }}
            platforms: linux/amd64,linux/arm64
            build-args: |
              NODE_VERSION=${{ env.NODE_VERSION }}




